### PR TITLE
Issue #24 addressed - added resource_filename parameter to AddResourceFile method

### PR DESCRIPTION
**Pull request by shawncrawley**
Added essential resource_filename parameter to AddResourceFile method since this method allows the passing of a file-like object, but requires that in this case, a resource_filename is also passed.

### CODE REVIEW

**Comment by shawncrawley** [comment]
@jbradberry This should be a lot easier to review.

**Comment by shawncrawley** [comment]
@jbradberry I'm not sure if you saw that I had made this new pull request. Just another heads up.

**Comment by jbradberry** [comment]
@shawncrawley nope, I hadn't, thanks for the heads-up.

**Comment by jbradberry** [comment]
@shawncrawley This seems reasonable to me.  :+1:

**Pull request merged**
