### PR TITLE
Function to retrieve resourcemap xml document

### PR DESCRIPTION
**Pull request by pkdash**

### CODE REVIEW

**Comment by pkdash** [comment]
@alvacouch can your review this?

**Comment by pkdash** [comment]
@alvacouch I have manually tested the new function to retrieve resource map document for a resource from a remote Hydroshare site.

**Comment by pkdash** [comment]
I think we probably picked up returning HTTP 403 from the examples in Django REST framework, I agree we should be returning 401. Should we be creating an issue both in this repo and Hydroshare to make this change?

**Comment by alvacouch** [comment]
@pkdash Probably it should be an issue. A low priority because most people use the client. But we should remember the practice and insure that all new code adheres to it.

**Comment by hyi** [comment]
@pkdash @alvacouch Here is some discussion thread on HTTP 403 vs 401 http://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses and I agree with this summary stated there that a 401 Unauthorized response should be used for missing or bad authentication, and a 403 Forbidden response should be used afterwards, when the user is authenticated but isn’t authorized to perform the requested operation on the given resource. So I think most of what we have been doing to use Http 403 is probably OK. 

Another note to keep in mind that I have just recently added a customized page 403.html to show a customized page for permission denied error. If we want to change those to 401, we need to add a corresponding customized 401.html page as well so that we don't lose the customized page response.

**Pull request merged**
